// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "ui.h"
#include "app_events.h"
 // mora sadržavati tipove i extern queue

void btn_clicked(lv_event_t *e)
{
    // Your code here
}

void blue_button_pressed(lv_event_t * e)
{
	// Your code here
}

void blue_button_clicked(lv_event_t * e)
{
	// Your code here
}

void green_button_clicked(lv_event_t * e)
{
	// Your code here
}

void red_button_clicked(lv_event_t * e)
{
	// Your code here
}

void BLUE_SCREEN_BUTTON_CLICKED(lv_event_t * e)
{
    AppMessage msg = {
        .source = SOURCE_GUI,
        .command = CMD_LED_BLUE
    };
    xQueueSend(led_switch_in, &msg, portMAX_DELAY);
}

void GREEN_SCREEN_BUTTON_CLICKED(lv_event_t * e)
{
    AppMessage msg = {
        .source = SOURCE_GUI,
        .command = CMD_LED_GREEN
    };
    xQueueSend(led_switch_in, &msg, portMAX_DELAY);
}


void RED_SCREEN_BUTTON_CLICKED(lv_event_t * e)
{
    AppMessage msg = {
        .source = SOURCE_GUI,
        .command = CMD_LED_RED
    };
    xQueueSend(led_switch_in, &msg, portMAX_DELAY);
}


void BLUE_FLICKER(lv_event_t * e)
{
    AppMessage msg = {
        .source = SOURCE_GUI,
        .command = CMD_LED_BLUE_FLICKER
    };
    xQueueSend(led_switch_in, &msg, portMAX_DELAY);
}

void GREEN_FLICKER(lv_event_t * e)
{
    AppMessage msg = {
        .source = SOURCE_GUI,
        .command = CMD_LED_GREEN_FLICKER
    };
    xQueueSend(led_switch_in, &msg, portMAX_DELAY);
}

void RED_FLICKER(lv_event_t * e)
{
    AppMessage msg = {
        .source = SOURCE_GUI,
        .command = CMD_LED_RED_FLICKER
    };
    xQueueSend(led_switch_in, &msg, portMAX_DELAY);
}
