// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void BLUE_SCREEN_BUTTON_CLICKED(lv_event_t * e);
void GREEN_SCREEN_BUTTON_CLICKED(lv_event_t * e);
void RED_SCREEN_BUTTON_CLICKED(lv_event_t * e);
void BLUE_FLICKER(lv_event_t * e);
void GREEN_FLICKER(lv_event_t * e);
void RED_FLICKER(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
