// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

void ui_Dijagnostika_screen_init(void)
{
    ui_Dijagnostika = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Dijagnostika, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button9 = lv_btn_create(ui_Dijagnostika);
    lv_obj_set_width(ui_Button9, 150);
    lv_obj_set_height(ui_Button9, 50);
    lv_obj_set_x(ui_Button9, -80);
    lv_obj_set_y(ui_Button9, -90);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "LED");

    ui_Button2 = lv_btn_create(ui_Dijagnostika);
    lv_obj_set_width(ui_Button2, 150);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 80);
    lv_obj_set_y(ui_Button2, -90);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button10 = lv_btn_create(ui_Dijagnostika);
    lv_obj_set_width(ui_Button10, 150);
    lv_obj_set_height(ui_Button10, 50);
    lv_obj_set_x(ui_Button10, 80);
    lv_obj_set_y(ui_Button10, -30);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button11 = lv_btn_create(ui_Dijagnostika);
    lv_obj_set_width(ui_Button11, 150);
    lv_obj_set_height(ui_Button11, 50);
    lv_obj_set_x(ui_Button11, -80);
    lv_obj_set_y(ui_Button11, -30);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button12 = lv_btn_create(ui_Dijagnostika);
    lv_obj_set_width(ui_Button12, 150);
    lv_obj_set_height(ui_Button12, 50);
    lv_obj_set_x(ui_Button12, -80);
    lv_obj_set_y(ui_Button12, 30);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button13 = lv_btn_create(ui_Dijagnostika);
    lv_obj_set_width(ui_Button13, 150);
    lv_obj_set_height(ui_Button13, 50);
    lv_obj_set_x(ui_Button13, 80);
    lv_obj_set_y(ui_Button13, 30);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BACK = lv_btn_create(ui_Dijagnostika);
    lv_obj_set_width(ui_BACK, 150);
    lv_obj_set_height(ui_BACK, 50);
    lv_obj_set_x(ui_BACK, 80);
    lv_obj_set_y(ui_BACK, 90);
    lv_obj_set_align(ui_BACK, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACK, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACK, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_BACK);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Main menu");

    ui_Button15 = lv_btn_create(ui_Dijagnostika);
    lv_obj_set_width(ui_Button15, 150);
    lv_obj_set_height(ui_Button15, 50);
    lv_obj_set_x(ui_Button15, -80);
    lv_obj_set_y(ui_Button15, 90);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BACK, ui_event_BACK, LV_EVENT_ALL, NULL);

}
