// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

void ui_Main_menu_screen_init(void)
{
    ui_Main_menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main_menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main_menu, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DijagnostikaBTN = lv_btn_create(ui_Main_menu);
    lv_obj_set_width(ui_DijagnostikaBTN, 100);
    lv_obj_set_height(ui_DijagnostikaBTN, 50);
    lv_obj_set_x(ui_DijagnostikaBTN, 0);
    lv_obj_set_y(ui_DijagnostikaBTN, 75);
    lv_obj_set_align(ui_DijagnostikaBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DijagnostikaBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DijagnostikaBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_DijagnostikaBTN);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Dijagnostika");

    lv_obj_add_event_cb(ui_DijagnostikaBTN, ui_event_DijagnostikaBTN, LV_EVENT_ALL, NULL);

}
